# Site settings
title: HEAD
description: "A free guide to <head> elements"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://htmlhead.dev" # the base hostname & protocol for your site (no trailing slash)
twitter_username: joshbuchea
github_username:  joshbuchea
google_analytics: UA-79520097-1
exclude: [readme.md]
sass:
  #style: compressed

# Build settings
markdown: kramdown

# Compress HTML
compress_html:
  clippings: all
  comments: []
  endings: [p, li, td]
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]
